export const users = [
    {
        id: 1,
        names: 'Juan Francisco',
        lastNames: 'Ponce Hernández',
        password: 'ifvfvfnnnfjvf',
        dateBirth: '1999-11-26 00:00:00.000000',
        cellPhone: '0987654321',
        document: '0987654321',
        email: 'juan@gmail.com',
        genderId: 1,
        officeId: 2,
        officeName: 'Rcto. El Piedrero',
        roles:[{id: 12, name: 'Odontologo'}],
        pregrade_university: '',
        postgrade_university: ''
    },
    {
        id: 2,
        names: 'María',
        lastNames: 'Cevallos Jimenez',
        password: 'jdnjvnfvjnvjnjn',
        dateBirth: '1999-11-26 00:00:00.000000',
        cellPhone: '0987654321',
        document: '0987654321',
        email: 'maria@gmail.com',
        genderId: 2,
        officeId: 1,
        officeName: 'Mapasingue',
        roles:[{id: 12, name: 'Odontologo'},{id: 14, name: 'Administrador'}],
        pregrade_university: '',
        postgrade_university: ''
    },
    {
        id: 3,
        names: 'Francisco Gabriel',
        lastNames: 'Hurtado Hurtado',
        password: 'mxvzvcssasfc2',
        dateBirth: '1999-11-26 00:00:00.000000',
        cellPhone: '0964412390',
        document: '0997654321',
        email: 'francisco@gmail.com',
        genderId: 1,
        officeId: 3,
        officeName: 'Rosario',
        roles:[{id: 13, name: 'Secretaria'}],
        pregrade_university: '',
        postgrade_university: ''
    },
]