const data = [
    {id: 1, name: 'Caries compuestas y complejas', price: 15},
    {id: 2, name: 'Sellantes', price: 10},
    {id: 3, name: 'Exodoncias simples de central a canino', price: 10},
    {id: 4, name: 'Exodoncias en niños', price: 10},
    {id: 5, name: 'Exodoncias complejas', price: 15},
    {id: 6, name: 'Exodoncia 3er molar superior erupcionado', price: 20},
    {id: 7, name: 'Exodoncia 3er molar superior retenido', price: 30},
    {id: 8, name: 'Exodoncia 3er molar inferior erupcionado', price: 30},
    {id: 9, name: 'Exodoncia 3er molar inferior retenido', price: 50},
    {id: 10, name: 'Gingivectomias y corte de frenillo (por arcada)', price: 30},
    {id: 11, name: 'Ortodoncia metálica', price: 80},
    {id: 12, name: 'Ortodoncia autoligado', price: 150},
    {id: 13, name: 'Ortodonica estética', price: 200},
    {id: 14, name: 'Controles ortodonica', price: 20},
    {id: 15, name: 'Reposición de brackets', price: 3},
    {id: 16, name: 'Reposición de tubos', price: 5},
    {id: 17, name: 'Ligas interdentales', price: 2},
    {id: 18, name: 'Blanqueamiento', price: 60},
    {id: 19, name: 'Endodoncia central a canino Bio', price: 90},
    {id: 20, name: 'Endodoncia central a canino Necro', price: 90},
    {id: 21, name: 'Endodoncia central a canino Retratamiento', price: 100},
    {id: 22, name: 'Endodoncia de premolares Bio', price: 120},
    {id: 23, name: 'Endodoncia de premolares Necro', price: 150},
    {id: 24, name: 'Endodoncia de premolares Retratamiento', price: 160},
    {id: 25, name: 'Endodoncia molar Bio', price: 180},
    {id: 26, name: 'Endodoncia premolar Necro', price: 200},
    {id: 27, name: 'Endodoncia premolar Retratamiento', price: 200},
    {id: 28, name: 'Postes fibra de vidrio', price: 30},
    {id: 29, name: 'IKER', price: 60},
    {id: 30, name: 'Protesis parciales acrilicas', price: 100},
    {id: 31, name: 'Protesis total acrilica', price: 120},
    {id: 32, name: 'Carillas resinas', price: 20},
    {id: 33, name: 'Carillas ceromero', price: 80},
    {id: 34, name: 'Lentes de contacto Emax', price: 180},
    {id: 35, name: 'Meriland metal porcelana', price: 150},
    {id: 36, name: 'Meriland ceromero', price: 100},
    {id: 37, name: 'Meriland zirconio', price: 300},
    {id: 38, name: 'Meriland Emax', price: 220},
    {id: 39, name: 'Coronas metal porcelana', price: 80},
    {id: 40, name: 'Corona disilicato', price: 200},
    {id: 41, name: 'Corona zirconio', price: 230},
    {id: 42, name: 'Corona ceromero', price: 80},
    {id: 43, name: 'Incrustación ceromero', price: 70},
    {id: 44, name: 'Incrustación zirconio', price: 150},
    {id: 45, name: 'Incrustación Emax', price: 120},
    {id: 46, name: 'Implantes', price: 800},
];

export default data;